/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libHero.so'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

union $781B27F37A2DA3C5D0084E69F313DC7D;
union $D1D0F511BF997F52624AFB2B0CE27B40;
struct $6ECA53571B8FCC125A3088582131FB6E;
struct CFTTGraphicsBuffer;
struct CGfxPostProcessBlitter_vtable;
struct CFTTGraphicsBuffer_vtable;
struct GraphicsDevice_vtable;

/* 1 */
struct __attribute__((aligned(4))) Elf32_Sym
{
  unsigned __int32 st_name;
  unsigned __int32 st_value;
  unsigned __int32 st_size;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
};

/* 2 */
struct Elf32_Rel
{
  unsigned __int32 r_offset;
  unsigned __int32 r_info;
};

/* 3 */
union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249
{
  unsigned __int32 d_val;
  unsigned __int32 d_ptr;
};

/* 4 */
struct Elf32_Dyn
{
  __int32 d_tag;
  union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249 d_un;
};

/* 5 */
struct Elf32_Verdef
{
  unsigned __int16 vd_version;
  unsigned __int16 vd_flags;
  unsigned __int16 vd_ndx;
  unsigned __int16 vd_cnt;
  unsigned __int32 vd_hash;
  unsigned __int32 vd_aux;
  unsigned __int32 vd_next;
};

/* 6 */
struct __attribute__((aligned(4))) Elf32_Verdaux
{
  unsigned __int32 vda_name;
  unsigned __int32 vda_next;
};

/* 7 */
struct __attribute__((aligned(4))) Elf32_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file;
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 8 */
struct __attribute__((aligned(4))) Elf32_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name;
  unsigned __int32 vna_next;
};

/* 9 */
typedef signed __int32 _Unwind_Sword;

/* 10 */
typedef unsigned __int32 _Unwind_Ptr;

/* 11 */
typedef unsigned __int32 _Unwind_Internal_Ptr;

/* 12 */
typedef unsigned __int32 _Unwind_Word;

/* 13 */
typedef int _Unwind_Action;

/* 14 */
typedef unsigned __int64 _Unwind_Exception_Class;

/* 15 */
enum $BDF88968CAE1EA74E42809B9AE857E7C
{
  _URC_NO_REASON = 0x0,
  _URC_FOREIGN_EXCEPTION_CAUGHT = 0x1,
  _URC_FATAL_PHASE2_ERROR = 0x2,
  _URC_FATAL_PHASE1_ERROR = 0x3,
  _URC_NORMAL_STOP = 0x4,
  _URC_END_OF_STACK = 0x5,
  _URC_HANDLER_FOUND = 0x6,
  _URC_INSTALL_CONTEXT = 0x7,
  _URC_CONTINUE_UNWIND = 0x8,
};

/* 16 */
typedef enum $BDF88968CAE1EA74E42809B9AE857E7C _Unwind_Reason_Code;

/* 17 */
struct _Unwind_Exception;

/* 18 */
struct _Unwind_Context;

/* 19 */
typedef void (__fastcall *_Unwind_Exception_Cleanup_Fn)(_Unwind_Reason_Code, struct _Unwind_Exception *);

/* 20 */
typedef _Unwind_Reason_Code (__fastcall *_Unwind_Personality_Fn)(int, _Unwind_Action, _Unwind_Exception_Class, struct _Unwind_Exception *, struct _Unwind_Context *);

/* 21 */
typedef _Unwind_Reason_Code (__fastcall *_Unwind_Stop_Fn)(int, _Unwind_Action, _Unwind_Exception_Class, struct _Unwind_Exception *, struct _Unwind_Context *, void *);

/* 22 */
typedef _Unwind_Sword __guard;

/* 23 */
struct tm
{
  int tm_sec;
  int tm_min;
  int tm_hour;
  int tm_mday;
  int tm_mon;
  int tm_year;
  int tm_wday;
  int tm_yday;
  int tm_isdst;
};

/* 24 */
struct sysinfo
{
  int uptime;
  unsigned int loads[3];
  unsigned int totalram;
  unsigned int freeram;
  unsigned int sharedram;
  unsigned int bufferram;
  unsigned int totalswap;
  unsigned int freeswap;
  unsigned __int16 procs;
  unsigned __int16 pad;
  unsigned int totalhigh;
  unsigned int freehigh;
  unsigned int mem_unit;
  char _f[8];
};

/* 25 */
typedef $781B27F37A2DA3C5D0084E69F313DC7D pthread_attr_t;

/* 26 */
union $781B27F37A2DA3C5D0084E69F313DC7D
{
  char __size[36];
  int __align;
};

/* 27 */
typedef $D1D0F511BF997F52624AFB2B0CE27B40 pthread_mutexattr_t;

/* 28 */
union $D1D0F511BF997F52624AFB2B0CE27B40
{
  char __size[4];
  int __align;
};

/* 30 */
typedef unsigned __int16 sa_family_t;

/* 29 */
struct sockaddr
{
  sa_family_t sa_family;
  char sa_data[14];
};

/* 34 */
typedef int __kernel_long_t;

/* 33 */
typedef __kernel_long_t __kernel_time_t;

/* 32 */
typedef __kernel_time_t __time_t;

/* 36 */
typedef __kernel_long_t __kernel_suseconds_t;

/* 35 */
typedef __kernel_suseconds_t __suseconds_t;

/* 31 */
struct timeval
{
  __time_t tv_sec;
  __suseconds_t tv_usec;
};

/* 37 */
typedef $6ECA53571B8FCC125A3088582131FB6E fd_set;

/* 39 */
typedef int __fd_mask;

/* 38 */
struct $6ECA53571B8FCC125A3088582131FB6E
{
  __fd_mask __fds_bits[32];
};

/* 43 */
typedef signed int int32_t;

/* 42 */
typedef int32_t __socklen_t;

/* 41 */
typedef __socklen_t socklen_t;

/* 40 */
struct addrinfo
{
  int ai_flags;
  int ai_family;
  int ai_socktype;
  int ai_protocol;
  socklen_t ai_addrlen;
  char *ai_canonname;
  sockaddr *ai_addr;
  addrinfo *ai_next;
};

/* 46 */
typedef unsigned int uint32_t;

/* 45 */
typedef uint32_t in_addr_t;

/* 44 */
struct in_addr
{
  in_addr_t s_addr;
};

/* 47 */
struct pollfd
{
  int fd;
  __int16 events;
  __int16 revents;
};

/* 48 */
struct CHeroAnalytics;

/* 49 */
struct CFE;

/* 50 */
struct CLoadingScreen;

/* 51 */
struct CDataBase;

/* 52 */
struct CDownloads;

/* 53 */
struct CFE3DPlayer;

/* 54 */
struct CGfxShadowMapManager;

/* 55 */
struct CFECloudMessages;

/* 56 */
struct CFEHeroScene;

/* 57 */
struct CFEKeyboard;

/* 58 */
struct CMessageBox;

/* 59 */
struct CMessageBoxHandler;

/* 60 */
struct CFEScreen;

/* 61 */
struct CFEEffects;

/* 62 */
struct CFESAndroidGraphics;

/* 63 */
struct CFESChooseHero;

/* 64 */
struct CGfxPostProcessRenderer;

/* 65 */
struct CFESChooseSideHero;

/* 66 */
struct CFESEditPlayer;

/* 67 */
struct CFESGame;

/* 68 */
struct CFESIntro;

/* 69 */
struct CFESLevelSelect;

/* 70 */
struct CFESMainMenu;

/* 71 */
struct CFESOptions;

/* 72 */
struct CFESPauseMenu;

/* 73 */
struct CFESShopHelper;

/* 74 */
struct CFESShop;

/* 75 */
struct CFESTemplate;

/* 76 */
struct CUIMsgContract;

/* 77 */
struct CUIMsgNewUpdate;

/* 78 */
struct CUIMsgPolaroid;

/* 79 */
struct CUIMsgProfile;

/* 80 */
struct CUIMsgPromotion;

/* 81 */
struct CUITile;

/* 82 */
struct CUIMsgShirt;

/* 83 */
struct CMessageBoxWithDownloadTile;

/* 84 */
struct CUIMsgShop;

/* 85 */
struct CUIMsgVideoAds;

/* 86 */
struct CUITileBasic;

/* 87 */
struct CUITileButton;

/* 88 */
struct CUITileButtonExpander;

/* 89 */
struct CUITileCredits;

/* 90 */
struct CUITileCrossPromotion;

/* 91 */
struct CUITileEnergy;

/* 92 */
struct CUITileFacebookFriends;

/* 93 */
struct CUITileGoldenBoot;

/* 94 */
struct CUITileGoldenBootPurchase;

/* 95 */
struct CUITileHeadShot;

/* 96 */
struct CUITileHUDText;

/* 97 */
struct CUITileItemSelector;

/* 98 */
struct CUITileLevel;

/* 99 */
struct CUITileLocked;

/* 100 */
struct CUITileNationality;

/* 101 */
struct CUITileNationalityLarge;

/* 102 */
struct CUITileNewspaper;

/* 103 */
struct CUITileNPMenu;

/* 104 */
struct TPhotoPost;

/* 105 */
struct CUITileOptionLang;

/* 106 */
struct CUITileOptionOnOff;

/* 107 */
struct CUITileOptionScale;

/* 108 */
struct CUITileOptionSpinBox;

/* 109 */
struct CUITilePageBG;

/* 110 */
struct CUITilePauseButton;

/* 111 */
struct CUITileScoreboard;

/* 112 */
struct CUIMsgShopButton;

/* 113 */
struct CUIMsgShopDownload;

/* 114 */
struct CUITileSideClock;

/* 115 */
struct CUITileSideClockLS;

/* 116 */
struct CUITileSideStory;

/* 117 */
struct CUITileSideStoryTicket;

/* 118 */
struct CUITileStars;

/* 119 */
struct CUITileStarsLS;

/* 120 */
struct CUITileSticker;

/* 121 */
struct CUITileUser;

/* 122 */
struct CUITileVideoAd;

/* 123 */
struct CUITileManager;

/* 124 */
struct CEasing;

/* 125 */
struct CRSplineF;

/* 126 */
struct CSpringSlider;

/* 127 */
struct CFEImages;

/* 128 */
struct CAnimManager;

/* 129 */
struct CBall;

/* 130 */
struct CBallProj;

/* 131 */
struct CGameFeats;

/* 132 */
struct CGameLoop;

/* 133 */
struct CPlayerManager;

/* 134 */
struct CNISAction;

/* 135 */
struct CNISActionFakeSub;

/* 136 */
struct CNISActionSetFormationPos;

/* 137 */
struct CNISActionWalkWithBall;

/* 138 */
struct CNISCamAction;

/* 139 */
struct CNISCamActionWait;

/* 140 */
struct CNISDirection;

/* 141 */
struct CNISExpInt;

/* 142 */
struct CNISExpression;

/* 143 */
struct CNISExpVector;

/* 144 */
struct CNISHeadAction;

/* 145 */
struct CNISInterface;

/* 146 */
struct CNISInterfaceDebug;

/* 147 */
struct CNISInterfaceFly;

/* 148 */
struct CNISAct;

/* 149 */
struct CNISAnimManager;

/* 150 */
struct CNISPlayerSeq;

/* 151 */
struct CNISScene;

/* 152 */
struct CNISSound;

/* 153 */
struct CNISStringUtil;

/* 154 */
struct CNISConstVectors;

/* 155 */
struct CNISRelativeConsts;

/* 156 */
struct CNISRelVariable;

/* 157 */
struct CFTTPPrimitive;

/* 158 */
struct CFTTPObject;

/* 159 */
struct CPlayer;

/* 160 */
struct CReplay;

/* 161 */
struct CFTTQuaternion32;

/* 162 */
struct CAnimLib;

/* 163 */
struct CGfxCharacter;

/* 164 */
struct CGFXFX;

/* 165 */
struct CGfxKits;

/* 166 */
struct CModelMan_ModelInfo;

/* 167 */
struct CModelManager;

/* 168 */
struct CGfxNIS;

/* 169 */
struct CGfxPlayer;

/* 170 */
struct CFTTPlane32;

/* 171 */
struct CGfxPostProcessBlitter
{
  CGfxPostProcessBlitter_vtable *vtable;
  CGfxPostProcessBlitter *Next;
};

/* 639 */
struct CGfxPostProcessBlitter_vtable
{
  int field_0;
  int field_4;
  int field_8;
  int field_C;
};

/* 172 */
struct CGfxPostProcess;

/* 173 */
struct CGfxProp;

/* 174 */
struct CResourceManager;

/* 175 */
struct CGraphicsRewindEffect;

/* 176 */
struct CPBRLighting;

/* 177 */
struct HalfConverter;

/* 178 */
struct CMyVulkanProjectSetup;

/* 179 */
struct CGfxStadiumProps;

/* 180 */
struct CGfxPodium;

/* 181 */
struct CGfxPlinth;

/* 182 */
struct CFTTColour;

/* 183 */
struct CGfxAdboard;

/* 184 */
struct CLiveAdboard;

/* 185 */
struct CAdElement;

/* 186 */
struct TAdPointInterpolator;

/* 187 */
struct TAdColourInterpolator;

/* 188 */
struct TAdFloatInterpolator;

/* 189 */
struct CGfxCrowd;

/* 190 */
struct TEdgeGroup;

/* 191 */
struct TGfxCrowdState;

/* 192 */
struct CGfxCloth;

/* 193 */
struct CFTTAABB32;

/* 194 */
struct TAABB;

/* 195 */
struct CGfxEnv;

/* 196 */
struct CGfxEnvironmentMap;

/* 197 */
struct CGfxFloodLights;

/* 198 */
struct CFTTGraph;

/* 199 */
struct GFXNET;

/* 200 */
struct AABB;

/* 201 */
struct Cubic;

/* 202 */
struct CGfxPitch;

/* 203 */
struct TStem;

/* 204 */
struct CGfxPitchLines
{
  int field_0;
  float field_4;
  int field_8;
  int field_C;
  float field_10;
  int field_14;
  int field_18;
  int field_1C;
  int field_20;
  float field_24;
  int field_28;
  int field_2C;
  int field_30;
  int field_34;
  float field_38;
  int field_3C;
  int field_40;
  int field_44;
  int field_48;
  float field_4C;
  int field_50;
  int field_54;
  int field_58;
  int field_5C;
  int field_60;
  int field_64;
  int field_68;
};

/* 205 */
struct TPitchLineGen;

/* 206 */
struct CGfxPitchLinePatch;

/* 207 */
struct TPitchLineCircle;

/* 208 */
struct TPitchLineRect;

/* 209 */
struct CFTTConvex;

/* 210 */
struct CGfxGroundShadow;

/* 211 */
struct CGfxShadow;

/* 212 */
struct CGFXSHADOWStaticShadow;

/* 213 */
struct TShadowAABB;

/* 214 */
struct CGfxShadowMap;

/* 215 */
struct CGfxShadowMapUniform;

/* 216 */
struct CInFlightCredits;

/* 217 */
struct CCurrency;

/* 218 */
struct TProfileDataCloud;

/* 219 */
struct CMyProfile;

/* 220 */
struct CProfileFeats;

/* 221 */
struct CGameSettings;

/* 222 */
struct CProfileStats;

/* 223 */
struct CUnlockables;

/* 224 */
struct CShaderSetup;

/* 225 */
struct CFreeHUD;

/* 226 */
struct CSideStoryProfile;

/* 227 */
struct CStoryCore;

/* 228 */
struct CStoryHUD;

/* 229 */
struct CStoryProfile;

/* 230 */
struct CStoryProfileStages;

/* 231 */
struct CStageManager;

/* 232 */
struct CFTTBannerAds;

/* 233 */
struct CFTTInterstitials;

/* 234 */
struct CFTTRewardedVideos;

/* 235 */
struct CFTTAndroidRewardedVideos;

/* 236 */
struct CFTTChartboost;

/* 237 */
struct CFTTAndroidChartboost;

/* 238 */
struct CFTTAndroidFBInterstitials;

/* 239 */
struct CFTTAnalytics;

/* 240 */
struct CFTTAWSKinesisFirehose;

/* 241 */
struct CFTTAndroidAnalytics;

/* 242 */
struct CFTTAudio;

/* 243 */
struct CFTTMusicPlayer;

/* 244 */
struct CFTTMemPool_Static;

/* 245 */
struct CFTTAudio_Bank;

/* 246 */
struct CFTTAudio_Patch;

/* 247 */
struct CFTTAudio_SoundPlayer;

/* 248 */
struct CFTTAudio_StreamHandler;

/* 249 */
struct CFTTFont2D;

/* 250 */
struct CFTTCamera;

/* 251 */
struct CFTTMaterial;

/* 252 */
struct CFTTMaterialManager;

/* 637 */
struct FTTPRIMTYPE
{
  int field_0;
};

/* 253 */
struct __cppobj CFTTRenderHelper
{
  FTTPRIMTYPE eFTTPRIMTYPE_0;
  int field_4;
  uint field_8;
  int len_indices_C;
  CFTTGraphicsBuffer *pGraphicsBuffer_10;
  CFTTGraphicsBuffer *pGraphicsBuffer_14;
  bool byte_18;
  int field_1C;
  uint vert_size_20;
  int vert_count_24;
  int len_Indices_28;
};

/* 635 */
struct CFTTGraphicsBuffer
{
  CFTTGraphicsBuffer_vtable *Vtable;
  int field_4;
  int field_8;
};

/* 640 */
struct CFTTGraphicsBuffer_vtable
{
  int field_0;
  int field_4;
  int (__fastcall *field_8)(CFTTGraphicsBuffer *);
  int field_C;
};

/* 254 */
struct CFTTShaderBuiltInConstants;

/* 255 */
struct CFTTUberShader;

/* 256 */
struct CFTTGraphicsDeviceOGLES;

/* 257 */
struct CFTTGLES2Wrapper;

/* 258 */
struct CFTTRenderTarget;

/* 259 */
struct CFTTGraphicsDevice;

/* 260 */
struct CFTTGraphicsDeviceOGLES3;

/* 261 */
struct CFTTUberShaderBlendMode;

/* 262 */
struct CFTTVulkanPipelineState;

/* 263 */
struct CFTTGraphicsDeviceVulkan;

/* 264 */
struct CFTTVulkanStreamAllocator;

/* 265 */
struct CFTTVulkanMemory;

/* 266 */
struct CFTTVulkanCommandPool;

/* 267 */
struct CFTTVulkanPipelineManager;

/* 268 */
struct CFTTVulkanProjectSetup;

/* 269 */
struct CFTTShaderProgram;

/* 270 */
struct CFTTGraphicsBufferVulkan;

/* 271 */
struct FTTVulkanMemoryChunk;

/* 272 */
struct CBlitter;

/* 273 */
struct CFTTBatchModelBin;

/* 274 */
struct CFTTBatchModelManager
{
  char field_0[1259];
  char field_4EB;
};

/* 275 */
struct CFTTBatchCache;

/* 276 */
struct TFTTCacheBucket;

/* 277 */
struct CFTTBatchCacheHashTable;

/* 278 */
struct TFTTCacheLookup;

/* 279 */
struct CFTTModel;

/* 280 */
struct CFTTAnimBlend;

/* 281 */
struct CFTTAnim;

/* 282 */
struct CFTT_FTMLoader;

/* 283 */
struct CFTTLangDatabase;

/* 284 */
struct CCustomTextEntry;

/* 285 */
struct CFTTFileSystem_PAK;

/* 286 */
struct CFTTFile_PAK;

/* 287 */
struct CFTTFileIterator_PAK;

/* 288 */
struct CFTTFileSystem;

/* 289 */
struct CFTTFile;

/* 290 */
struct CFTTTexLoadOptions;

/* 291 */
struct CFTTTexture;

/* 292 */
struct CFTTTextureCache;

/* 293 */
struct CFTTTexMan_TexInfo;

/* 294 */
struct CFTTTextureManager;

/* 295 */
struct CFTTRenderToTextureOGLES;

/* 296 */
struct CFTTTextureOGLES;

/* 297 */
struct CFTTRenderBufferVulkan;

/* 298 */
struct CFTTRenderTargetVulkan;

/* 299 */
struct CFTTRenderBuffer;

/* 300 */
struct CFTTRenderToTextureVulkan;

/* 301 */
struct CFTTTextureVulkan;

/* 302 */
struct CFTTRenderToTexture;

/* 303 */
struct CFTTRenderBufferOGLES;

/* 304 */
struct CFTTRenderTargetOGLES;

/* 305 */
struct CFTTTextureAtlas;

/* 306 */
struct CFTTTextureWriter;

/* 307 */
struct CFTTTextureData;

/* 308 */
struct CFTTTextureWriterDropMip;

/* 309 */
struct CFTTXmlReaderNode;

/* 310 */
struct CFTTXmlReader;

/* 311 */
struct CFTTXmlWriterNode;

/* 312 */
struct CFTTXmlWriter;

/* 313 */
struct CFTTXmlReaderWriter;

/* 314 */
struct CFTTJson;

/* 315 */
struct CFTTJSONReaderNode;

/* 316 */
struct CFTTJsonReader;

/* 317 */
struct rapidjson::ParseResult;

/* 318 */
struct rapidjson::CrtAllocator;

/* 319 */
struct rapidjson::internal;

/* 320 */
struct CFTTColourHsv;

/* 321 */
struct CFTTColourHsl;

/* 322 */
struct CFTTDevice;

/* 323 */
struct CFTTDisplayAchievements;

/* 324 */
struct CFTTFile_ZLib;

/* 325 */
struct CFTTFile_Buffered;

/* 326 */
struct CFTTFile_ROM;

/* 327 */
struct CFTTFile_RAM;

/* 328 */
struct CFTTFile_AsyncQueue;

/* 329 */
struct CFTTFile_AsyncHandler;

/* 330 */
struct CFTTJob;

/* 331 */
struct CFTTJobList;

/* 332 */
struct CFTTLocalNotification;

/* 333 */
struct CFTTMemAutoShutdown;

/* 334 */
struct CFTTRandomNumberGeneratorThreadsafe;

/* 335 */
struct CFTTRandomNumberGenerator;

/* 336 */
struct CFTTSaveFile;

/* 337 */
struct CFTTSerialize;

/* 338 */
struct CFTTTime;

/* 339 */
struct CFTTDateTimeUtils;

/* 340 */
struct CDatabaseEntry;

/* 341 */
struct CFTTFile_Android;

/* 342 */
struct CFTTFile_AndroidMemMap;

/* 343 */
struct CFTTFileSystem_Android;

/* 344 */
struct CFTTFileIterator_Android;

/* 345 */
struct CFTTFile_AndroidDocs;

/* 346 */
struct CFTTMemPrivate;

/* 347 */
struct FTTThread;

/* 348 */
struct FTTMutex;

/* 349 */
struct FTTSemaphore;

/* 350 */
struct CFTTFacebook;

/* 351 */
struct CAWSRequestObject;

/* 352 */
struct CFTTHttpDownload;

/* 353 */
struct CFTTNetIAP;

/* 354 */
struct CFTTNetIAPValidation;

/* 355 */
struct CFTTSocialNetworking;

/* 356 */
struct CFTTAndroidFacebook;

/* 357 */
struct CFTTGoogleSavedGames;

/* 358 */
struct CFTTHttpDownload_Android;

/* 359 */
struct CFTTHttpDownload_Platform;

/* 360 */
struct CDownloadRequest;

/* 361 */
struct CFTTNetConnBase;

/* 362 */
struct CFTTNetLanLobby;

/* 363 */
struct CFTTNetLanSocket;

/* 364 */
struct CFTTNetConn_RakNet;

/* 365 */
struct TPunchthroughConfig;

/* 366 */
struct CLobbyServerDNSHelper;

/* 367 */
struct RakNet::NatPunchthroughDebugInterface_PacketLogger;

/* 368 */
struct RakNet::PunchthroughConfiguration;

/* 369 */
struct RakNet::NatPunchthroughClient;

/* 370 */
struct RakNet::NatPunchthroughDebugInterface;

/* 371 */
struct RakNet::PluginInterface2;

/* 372 */
struct RakNet;

/* 373 */
struct RakNet::RNS2_Berkley;

/* 374 */
struct RakNet::RakNetSocket2;

/* 375 */
struct RakNet::IRNS2_Berkley;

/* 376 */
struct RakNet::SocketDescriptor;

/* 377 */
struct RakNet::SystemAddress;

/* 378 */
struct RakNet::RakNetGUID;

/* 379 */
struct RakNet::RakPeer;

/* 380 */
struct RakNet::RakPeerInterface;

/* 381 */
struct RakNet::RakNetRandom;

/* 382 */
struct RakNet::RakString;

/* 383 */
struct RakNet::RakThread;

/* 384 */
struct RakNet::BPSTracker::TimeAndValue2;

/* 385 */
struct RakNet::BPSTracker;

/* 386 */
struct RakNet::ReliabilityLayer;

/* 387 */
struct RakNet::SimpleMutex;

/* 388 */
struct RakNet::StringCompressor;

/* 389 */
struct RakNet::StringTable;

/* 390 */
struct RakNet::TCPInterface;

/* 391 */
struct RakNet::RemoteClient;

/* 392 */
struct WSAStartupSingleton;

/* 393 */
struct RakNet::BitStream;

/* 394 */
struct RakNet::CCRakNetSlidingWindow;

/* 395 */
struct DataStructures::ByteQueue;

/* 396 */
struct RakNet::HuffmanEncodingTree;

/* 397 */
struct RakNet::SocketLayer;

/* 398 */
struct CSHA1;

/* 399 */
struct CFTTCircularBuffer;

/* 400 */
struct CFESTitle;

/* 401 */
struct CFTTSystemFontCached;

/* 402 */
struct CUITileScroller;

/* 403 */
struct CNISActionManagerFollow;

/* 404 */
struct CNISActionSad;

/* 405 */
struct CGfxFakePlayer;

/* 406 */
struct CGfxStaticShirt;

/* 407 */
struct CGfxSubBoard;

/* 408 */
struct CFTTNavMesh;

/* 409 */
struct CMatchSetup;

/* 410 */
struct CGFXLensFlare;

/* 411 */
struct CGraphicsTexLoadOptions;

/* 412 */
struct CGfxPrecipitation;

/* 413 */
struct TSocialNetworkingUpdatePreferences;

/* 414 */
struct CStoryTutorial;

/* 415 */
struct CFTTAndroidDevice;

/* 416 */
struct CFTTFBInterstitials;

/* 417 */
struct CFTTJobQueue;

/* 418 */
struct CFTTMemPool_Resizing;

/* 419 */
struct CFTTVulkanSetup;

/* 420 */
struct CFTTShaderProgramOGLES;

/* 421 */
struct CFTTShaderProgramVulkan;

/* 422 */
struct CFTTBMMMatrixCache;

/* 423 */
struct CFTTJsonMemWrapper;

/* 424 */
struct CFTTAndroidLocalNotification;

/* 425 */
struct CFTTNetAWSRequest;

/* 426 */
struct CFTTGooglePlus;

/* 427 */
struct CFTTAmazonGameCircle;

/* 428 */
struct CFTTSocialScores;

/* 429 */
struct CFTTAndroidAmazonGameCircle;

/* 430 */
struct CFTTAndroidGooglePlus;

/* 431 */
struct RakNet::CFTTNetConnRakNetPeer;

/* 432 */
struct RakNet::NatTypeDetectionClient;

/* 433 */
struct RakNet::Packet;

/* 434 */
struct RakNet::RNS2_Linux;

/* 435 */
struct RakNet::SignaledEvent;

/* 436 */
struct TIAPSaveData;

/* 437 */
struct RakNet::RakNetSocket2Allocator;

/* 438 */
struct TAdjustInitParams;

/* 439 */
struct CFTTRandom;

/* 440 */
struct CFESCredits;

/* 441 */
struct CFESPlayerName;

/* 442 */
struct CUIMsgFacebookFriend;

/* 443 */
struct CUIMsgPromotionItem;

/* 444 */
struct UIMsgSeasonComplete;

/* 445 */
struct CUIMsgSideStory;

/* 446 */
struct CUITileNumberSelector;

/* 447 */
struct CUITileSkinColour;

/* 448 */
struct CUITileActions;

/* 449 */
struct CNISActionFollow;

/* 450 */
struct CNISActionHappy;

/* 451 */
struct CNISActionHide;

/* 452 */
struct CNISActionIdle;

/* 453 */
struct CNISActionMove;

/* 454 */
struct CNISActionPickUpBall;

/* 455 */
struct CNISActionPlayAnim;

/* 456 */
struct CNISActionPutBallDown;

/* 457 */
struct CNISActionSetPos;

/* 458 */
struct CNISActionStop;

/* 459 */
struct CNISActionWait;

/* 460 */
struct CNISCamActionFollow;

/* 461 */
struct CNISCamActionFollowBasic;

/* 462 */
struct CNISCamActionMove;

/* 463 */
struct CNISCamActionMoveBasic;

/* 464 */
struct CNISCamActionSetPos;

/* 465 */
struct CNISCamActionSetPosBasic;

/* 466 */
struct CFTTPPPolyhedron;

/* 467 */
struct CFTTPPSphere;

/* 468 */
struct CFTTPPBox;

/* 469 */
struct CFTTPPCone;

/* 470 */
struct CFTTPPCylinder;

/* 471 */
struct CBallShader;

/* 472 */
struct CGFXFlag;

/* 473 */
struct CPlayerShader;

/* 474 */
struct CVHSEffectsShader;

/* 475 */
struct CDOFShrinkShader;

/* 476 */
struct CPPBlendShader;

/* 477 */
struct CGfxIngameRenderer;

/* 478 */
struct CFTTMatSetupData;

/* 479 */
struct CAdElImage;

/* 480 */
struct TAdPointEaser;

/* 481 */
struct TAdPointSpline;

/* 482 */
struct TAdColourEaser;

/* 483 */
struct TAdFloatEaser;

/* 484 */
struct FTTAtlasGenerator;

/* 485 */
struct TMatrix33;

/* 486 */
struct CGfxEnvMapRenderer;

/* 487 */
struct CGfxGlareManager;

/* 488 */
struct CPitchShader;

/* 489 */
struct CCircle2dShader;

/* 490 */
struct CGfxSky;

/* 491 */
struct TProfileData;

/* 492 */
struct TAudioOptions;

/* 493 */
struct TMetricsOptions;

/* 494 */
struct CBlurVShader;

/* 495 */
struct CColourMulti2dShader;

/* 496 */
struct CCrowdCardShader;

/* 497 */
struct CCrowdFlagShader;

/* 498 */
struct CCrowdNewShader;

/* 499 */
struct CDebugDepthShader;

/* 500 */
struct CDOFCombineShader;

/* 501 */
struct CDressingRoomShader;

/* 502 */
struct CGaussianNewShader;

/* 503 */
struct CGaussianShader;

/* 504 */
struct CGlareOccShader;

/* 505 */
struct CGlareRadialShader;

/* 506 */
struct CGoalNetShader;

/* 507 */
struct CGravelShader;

/* 508 */
struct CIntegrateBRDFShader;

/* 509 */
struct CKitGenShader;

/* 510 */
struct CLegacyLitShader;

/* 511 */
struct CLinearDepthShader;

/* 512 */
struct CPackedCombineShader;

/* 513 */
struct CPartAdditive2dShader;

/* 514 */
struct CPerfTest2dShader;

/* 515 */
struct CPhotoPostShader;

/* 516 */
struct CPitchCircleShader;

/* 517 */
struct CPitchPostShader;

/* 518 */
struct CPolaroid2dShader;

/* 519 */
struct CPPBlitShader;

/* 520 */
struct CPrecipitationShader;

/* 521 */
struct CRawDiffuseShader;

/* 522 */
struct CRawEnvShader;

/* 523 */
struct CRawSpecularShader;

/* 524 */
struct CSDFFontVisFBShader;

/* 525 */
struct CShadowBatchShader;

/* 526 */
struct CShadowMapShader;

/* 527 */
struct CShadowRenderShader;

/* 528 */
struct CSheen2dShader;

/* 529 */
struct CStadiumShader;

/* 530 */
struct TStorySeason;

/* 531 */
struct TPoint3D;

/* 532 */
struct TPoint;

/* 533 */
struct CXmlUtil;

/* 534 */
struct CFTTFontSDFShader;

/* 535 */
struct CFTTGraphicsBufferOGLES;

/* 536 */
struct FTTVulkanChunkAllocator;

/* 537 */
struct CFTT2d_Shader;

/* 538 */
struct CFTT3dGenShader;

/* 539 */
struct CFTTCubemapShader;

/* 540 */
struct CTouchStateInternal;

/* 541 */
struct CFTTCube2DShader;

/* 542 */
struct CFTTXmlMemWrapper;

/* 543 */
struct CFTTCloud;

/* 544 */
struct CFTTFile_AsyncImmediate;

/* 545 */
struct CFTTFileSystem_APKX;

/* 546 */
struct CIAPResponse;

/* 547 */
struct CFTTNetPCP;

/* 548 */
struct CFTTNetConnLan;

/* 549 */
struct RakNet::NatPunchthroughDebugInterface_Printf;

/* 550 */
struct RakNet::AddressOrGUID;

/* 551 */
struct TAnalyticsEventParams;

/* 552 */
struct TPlayerInfoLight;

/* 553 */
struct CTexLoadHelper;

/* 554 */
struct CUIMsgShopItem;

/* 555 */
struct CUITileTextSelector;

/* 556 */
struct CNISAnimList;

/* 557 */
struct CNISXmlReader;

/* 558 */
struct CNISConsts;

/* 559 */
struct CFTTPhysics;

/* 560 */
struct CGfxTrophy;

/* 561 */
struct CAdElShape;

/* 562 */
struct CAdElText;

/* 563 */
struct TAdColourSpline;

/* 564 */
struct TAdFloatSpline;

/* 565 */
struct CAdElRectangle;

/* 566 */
struct CAdElCircle;

/* 567 */
struct CGfxCornerFlag;

/* 568 */
struct TFTTFace;

/* 569 */
struct CGfxShadowMapPSSM;

/* 570 */
struct TMoveClubs;

/* 571 */
struct CStage;

/* 572 */
struct CSeason;

/* 573 */
struct TPoint16;

/* 574 */
struct CCallbackCriticalSection;

/* 575 */
struct COGLESCpuBuffer;

/* 576 */
struct CFTTSkinningTask;

/* 577 */
struct TModelAABBDC;

/* 578 */
struct CFTTRandomThreadsafe;

/* 579 */
struct CDownloadRequest_Android;

/* 580 */
struct RakNet::NatPunchthroughClient::SendPing;

/* 581 */
struct RakNet::NatPunchthroughClient::AddrAndGuid;

/* 582 */
struct RakNet::NatPunchthroughClient::DSTAndFac;

/* 583 */
struct RakNet::RNS2_SendParameters;

/* 584 */
struct RakNet::LocklessUint32_t;

/* 585 */
struct TNMAStar;

/* 586 */
struct CGfxCrowdFlagPhysics;

/* 587 */
struct TSideStoryProfileData;

/* 588 */
struct TStoryProfileData;

/* 589 */
struct TStageOperation;

/* 590 */
struct TModelSplit;

/* 591 */
struct CFTTAndroidGraphicsSettings;

/* 592 */
struct CFTTAndroidKeychainAccess;

/* 593 */
struct RakStringCleanup;

/* 594 */
struct DatagramHeaderFormat;

/* 595 */
struct CGfxCrowdFlagRender;

/* 596 */
struct CGfxCrowdCardGroup;

/* 597 */
struct CGfxGravel;

/* 598 */
struct TFTTAudio_MusicPlayerNative;

/* 599 */
struct CFTTNativeDialog;

/* 600 */
struct CFTTServerTime;

/* 601 */
struct CUIMsgRewind;

/* 602 */
struct CGFXSpec;

/* 603 */
struct CAndroidBQPlayer;

/* 604 */
struct RakNet::RakPeer::RemoteSystemStruct;

/* 605 */
struct CSupportDownload;

/* 606 */
struct CrowdTextureCreationData;

/* 607 */
struct TCrowdMember;

/* 608 */
struct CCustomTextInfo;

/* 609 */
struct CDeviceReimbursement;

/* 610 */
struct CFTTMem;

/* 611 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 612 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 613 */
typedef __n64 int8x8_t;

/* 614 */
typedef __n64 uint8x8_t;

/* 615 */
typedef __n64 int16x4_t;

/* 616 */
typedef __n64 int32x2_t;

/* 617 */
typedef __n64 uint16x4_t;

/* 618 */
typedef __n64 uint32x2_t;

/* 619 */
typedef __n128 int8x16_t;

/* 620 */
typedef __n128 int16x8_t;

/* 621 */
typedef __n128 int32x4_t;

/* 622 */
typedef __n128 int64x2_t;

/* 623 */
typedef __n128 uint8x16_t;

/* 624 */
typedef __n128 uint16x8_t;

/* 625 */
typedef __n128 uint32x4_t;

/* 626 */
typedef __n128 uint64x2_t;

/* 627 */
typedef __n64 poly8x8_t;

/* 628 */
typedef __n64 poly16x4_t;

/* 629 */
typedef __n128 poly16x8_t;

/* 630 */
typedef __n128 poly8x16_t;

/* 631 */
typedef __n64 float32x2_t;

/* 632 */
typedef __n128 float32x4_t;

/* 633 */
typedef __n128 float64x2_t;

/* 634 */
typedef __n128 poly128_t;

/* 636 */
struct CFTTMatrix32
{
  int field_0;
};

/* 638 */
struct CFTTRenderHelper_InitParams
{
  int field_0;
};

/* 641 */
struct __attribute__((packed)) __attribute__((aligned(4))) VERTICES_INFO
{
  int field_0;
  int field_4;
  float field_8;
  int field_C;
  int field_10;
  int field_14;
  float field_18;
  int field_1C;
  float field_20;
  int field_24;
  float field_28;
  int field_2C;
  int field_30;
  float field_34;
  float field_38;
  int field_3C;
  double field_40;
  float field_48;
  float field_4C;
  float field_50;
  int field_54;
  float field_58;
  float field_5C;
  int field_60;
};

/* 642 */
struct CFTTFrustum32;

/* 643 */
struct GraphicsDevice
{
  GraphicsDevice_vtable *vtable;
  int field_4;
  int field_8;
  int field_C;
  int field_10;
  int field_14;
  int field_18;
  int field_1C;
  int field_20;
  int field_24;
  int field_28;
};

/* 644 */
struct GraphicsDevice_vtable
{
  int field_0;
  int field_4;
  int field_8;
  int field_C;
  int field_10;
  int field_14;
  int (__fastcall *field_18)(GraphicsDevice *);
  int field_1C;
  int field_20;
  int field_24;
  int field_28;
  int (*field_2C)(void);
  int field_30;
  int (__fastcall *field_34)(GraphicsDevice *);
  int field_38;
  int (__fastcall *field_3C)(GraphicsDevice *);
  int (__fastcall *field_40)(GraphicsDevice *);
  int field_44;
  int field_48;
  int (__fastcall *ARGBToPlatformU32_2)(GraphicsDevice *, unsigned int);
  int field_50;
  int field_54;
  int field_58;
  int field_5C;
  int field_60;
  int field_64;
  int field_68;
  int field_6C;
  int field_70;
  int field_74;
  int field_78;
  int field_7C;
  int field_80;
  int field_84;
  int field_88;
  int field_8C;
  int field_90;
  int field_94;
  int field_98;
  int field_9C;
  int field_A0;
  int field_A4;
  int field_A8;
  int (__fastcall *field_AC)(GraphicsDevice *, int, int);
  int field_B0;
};

/* 645 */
struct __attribute__((packed)) __attribute__((aligned(4))) CGfxPostProcessSetup
{
  float field_0;
  float field_4;
  int field_8;
  int field_C;
  int field_10;
  float field_14;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  int field_1C;
  int field_20;
  int field_24;
  char field_28;
  char field_29;
  char field_2A;
  char field_2B;
  float field_2C;
  int field_30;
  char field_34;
  char field_35;
  char field_36;
  char field_37;
  int field_38;
  double field_3C;
  int field_44;
  int field_48;
  int field_4C;
  double field_50;
  char field_58[12];
  int field_64;
  int field_68;
  int field_6C;
  char field_70[100];
  int field_D4;
  int field_D8;
  double field_DC;
  int field_E4;
  int field_E8;
  int field_EC;
  double field_F0;
  char field_F8[16];
  int field_108;
  int field_10C;
  double field_110;
  char field_118[32];
  int field_138;
  int field_13C;
  __int16 field_140;
  __int16 field_142;
  int field_144;
  int field_148;
  int field_14C;
  char field_150;
  char field_151;
  char field_152;
  char field_153;
  int field_154[4];
  char field_164;
  char field_165;
  char field_166;
  char field_167;
  double field_168;
  float field_170;
  int field_174;
  char field_178;
  char field_179;
  char field_17A;
  char field_17B;
  int field_17C;
  int field_180;
  char field_184[32];
  int field_1A4[5];
  char field_1B8;
  char field_1B9;
  char field_1BA;
  char field_1BB;
  int field_1BC;
  float field_1C0;
  int field_1C4;
  int field_1C8;
};

/* 646 */
struct CGfxPitchLines_vtable
{
  int field_0;
  int field_4;
};

/* 647 */
struct GFXSPEC_pSpec
{
  char field_0[68];
  int field_44;
  int field_48;
};

